# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "debian/jessie64"

  if Vagrant.has_plugin?("vagrant-timezone")
    config.timezone.value = "Europe/Bucharest"
  end

  config.vm.provision :shell, :inline => <<-EOT
     sudo sed -i '/LC_ALL=/d' /etc/default/locale
     echo 'LC_ALL="en_US.UTF-8"' |sudo tee -a /etc/default/locale
  EOT

  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.customize ["modifyvm", :id, "--cpus", 1]
    # v.gui = true
  end

  config.vm.synced_folder "..", "/go-ethereum", owner: "root", group: "root"

  PORT = 30310
  config.vm.provision :shell, :path => "bootstrap.sh"
  config.vm.define "geth1", primary: true do |geth1|
    # geth1.vm.network "public_network", ip: "192.168.50.2", bridge: "eth0"
    geth1.vm.network "private_network", ip: "192.168.50.2"
    config.vm.network "forwarded_port", guest: PORT, host: PORT
    geth1.vm.provider :virtualbox do |vb|
      #
      # # default router
      # config.vm.provision "shell",
      #   run: "always",
      #   inline: "route add default gw 192.168.50.1"
      #
      # # delete default gw on eth0
      # config.vm.provision "shell",
      #   run: "always",
      #   inline: "eval `route -n | awk '{ if ($8 ==\"eth1\" && $2 != \"0.0.0.0\") print \"route del default gw \" $2; }'`"
      vb.memory = 4096
      vb.customize ["modifyvm", :id, "--cpus", 2]
    end

    config.vm.provision :shell, :run => "always", :path => "scripts/startGeth.sh", :args => PORT
  end
end
